# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://RilezLed.github.io/'
baseurl:             'journal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Riley Ledezma
  url:               None
  email:             magicpunkdude@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
